/**
 * fetch_ibm_daily.js
 * Downloads IBM daily adjusted-close prices from Yahoo Finance (1962-01-02 to today)
 * and writes them as IBM_DAILY_PRICES into ../data.js as a new top-level variable.
 *
 * Run from the project root:
 *   node annualreportsdashboard/pipeline/fetch_ibm_daily.js
 *
 * Requires Node 18+ (native fetch). No npm packages needed.
 */

const fs   = require("fs");
const path = require("path");
const https = require("https");

// Yahoo Finance v8 chart endpoint — returns OHLCV + adjclose
const SYMBOL    = "IBM";
const FROM_UNIX = Math.floor(new Date("1962-01-01").getTime() / 1000);
const TO_UNIX   = Math.floor(Date.now() / 1000);
const URL       = `https://query1.finance.yahoo.com/v8/finance/chart/${SYMBOL}?interval=1d&period1=${FROM_UNIX}&period2=${TO_UNIX}&events=history&includeAdjustedClose=true`;
const OUT_FILE  = path.join(__dirname, "..", "ibm_daily_prices.js");

function get(url) {
  return new Promise((resolve, reject) => {
    const opts = { headers: { "User-Agent": "Mozilla/5.0" } };
    https.get(url, opts, res => {
      let data = "";
      res.on("data", c => data += c);
      res.on("end", () => resolve(data));
    }).on("error", reject);
  });
}

(async () => {
  console.log("Fetching IBM daily prices from Yahoo Finance…");
  const raw  = await get(URL);
  const json = JSON.parse(raw);
  const result = json.chart.result[0];

  const timestamps  = result.timestamp;
  const adjClose    = result.indicators.adjclose[0].adjclose;

  // Build compact array: ["YYYY-MM-DD", price] — skip nulls
  const pairs = [];
  for (let i = 0; i < timestamps.length; i++) {
    const price = adjClose[i];
    if (price == null) continue;
    const d = new Date(timestamps[i] * 1000);
    const dateStr = d.toISOString().slice(0, 10);
    pairs.push([dateStr, Math.round(price * 100) / 100]);
  }

  const js = `/* AUTO-GENERATED by pipeline/fetch_ibm_daily.js — do not edit by hand.
   IBM daily adjusted-close prices from Yahoo Finance.
   Each entry: ["YYYY-MM-DD", price_in_usd] */
window.IBM_DAILY_PRICES = ${JSON.stringify(pairs)};
`;

  fs.writeFileSync(OUT_FILE, js, "utf8");
  console.log(`✓ Written ${pairs.length} daily price points to ${OUT_FILE}`);
  console.log(`  Date range: ${pairs[0][0]} → ${pairs[pairs.length-1][0]}`);
})();
